spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/votes
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
